server:
  port: 8901
spring:
  application:
    name: eureka-server
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
eureka:
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 10000
  instance:
    instance-id: 192.168.0.54:eureka-server:8901
    hostname: 192.168.0.54
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http:192.168.0.54:8901/eureka/



