arb:
  service:
    name: eureka-server
    port: 8901

server:
  port: ${arb.service.port}
spring:
  application: 
    name: ${arb.service.name}
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
  rabbitmq:
    host: ${arb.rabbitmq.url}
    port: 5672
    username: ${arb.rabbitmq.username}
    password: ${arb.rabbitmq.password}
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
eureka:
  server:
    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 10000
---
spring:
  profiles: local
eureka:
  instance:
    instance-id: localhost:${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
arb:
  rabbitmq:
    url: 192.168.0.100
    username: Arbfintech
    password: Arbfintech


