arb:
  service:
    name: microservice-foo
    port: 8889

eureka:
  instance:
    instance-id: 192.168.0.54:microservice-foo:8889
    hostname: 192.168.0.54
    ip-address: 192.168.0.54
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://192.168.0.54:8901/eureka/
feign:
  client:
    config:
      microservice-business:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-lead:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-loan:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-payment:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-collect:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-maintenance:
        connectTimeout: 60000
        readTimeout: 60000
      cache-server:
        connectTimeout: 60000
        readTimeout: 60000
      auth-server:
        connectTimeout: 60000
        readTimeout: 60000
    httpclient:
      connection-timeout: 60000
  hystrix:
    enabled: true
server:
  port: 8889
  max-http-header-size: 10240000
  tomcat:
    max-http-post-size: -1
spring:
  application:
    name: microservice-foo
  mvc:
    static-path-pattern: /**
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: -1
      max-request-size: -1
