#自定义配置
arb:
  service:
    name: microservice-business
    port: 8802

eureka:
  instance:
    instance-id: ${arb.service.url}:${spring.application.name}:${server.port}
    hostname: ${arb.service.url}
    ip-address: ${arb.service.url}
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://${arb.eureka.url}:8901/eureka/

spring:
  application:
    name: ${arb.service.name}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${arb.database.url}/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: ${arb.database.username}
    password: ${arb.database.password}
    test-on-borrow: true                      # 指明是否从池中取出连接前进行检验，如果检验失败，则从池中取出连接并尝试取出另一个
    test-while-idle: true                     # 指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
    time-between-eviction-runs-millis: 60000  # 在空闲连接回收器线程运行期间休眠的时间值，姨毫秒为单位。如果设置为非整数，则不运行空闲连接回收器线程
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
    show-sql: false

feign:
  client:
    config:
      cache-server:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-maintenance:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-payment:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-collect:
        connectTimeout: 60000
        readTimeout: 60000
  httpclient:
    connection-timeout: 60000

server:
  max-http-header-size: 10240000
  port: ${arb.service.port}
logging:
  config: classpath:log4j2.yml
---
spring:
  profiles: release
  eureka:
    url: china-dev.vertical.arbcalls.com
  database:
    url: china-dev.vertical.arbcalls.com
    username: root
    password: arbfintech
---
spring:
  profiles: develop
arb:
  eureka:
    url: panda.arbfintech.com
  service:
    url: 54.255.235.134
  database:
    url: arb-panda.cuxwfpxsyc7c.ap-southeast-1.rds.amazonaws.com
    username: panda_admin
    password: uGEqetW#a8uEKA2z
---
spring:
  profiles: slave_debug
arb:
  eureka:
    url: 192.168.0.100
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
---
spring:
  profiles: slave-23
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.23
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
---
spring:
  profiles: slave-12
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.12
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
---
spring:
  profiles: test
arb:
  eureka:
    url: localhost
  database:
    url: localhost
    username: root
    password: arbfintech

---
spring:
  profiles: local
arb:
  eureka:
    url: localhost
  service:
    url: localhost
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    username: Arbfintech
    password: Arbfintech
logging:
  level:
    com:
      arbfintech: DEBUG
---
spring:
  profiles: master
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.xx
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech

---
spring:
  profiles: slave-22
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.22
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
---
spring:
  profiles: slave-12
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.22
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
---
spring:
  profiles: slave-55
arb:
  eureka:
    url: 192.168.0.100
  service:
    url: 192.168.0.55
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech

---
spring:
  profiles: user-99
arb:
  eureka:
    url: 192.168.0.99
  service:
    url: 192.168.0.99
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech

---
spring:
  profiles: slave-45
arb:
  eureka:
    url: 192.168.0.45
  service:
    url: 192.168.0.45
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech

---
spring:
  profiles: slave-54
arb:
  eureka:
    url: 192.168.0.54
  service:
    url: 192.168.0.54
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
