

eureka:
  instance:
    instance-id: 192.168.0.54:station-panda:8081
    hostname: 192.168.0.54
    ip-address: 192.168.0.54
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://192.168.0.54:8901/eureka/
feign:
  client:
    config:
      microservice-business:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-lead:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-loan:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-payment:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-collect:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-maintenance:
        connectTimeout: 60000
        readTimeout: 60000
      cache-server:
        connectTimeout: 60000
        readTimeout: 60000
      auth-server:
        connectTimeout: 60000
        readTimeout: 60000
      maintenance-restapi:
        connectTimeout: 60000
        readTimeout: 60000
    httpclient:
      connection-timeout: 60000
#  hystrix:
#    enabled: true
server:
  port: 8081
  max-http-header-size: 10240000
  tomcat:
    max-http-post-size: -1
  ssl:
    enabled-protocols: TLSv1.2
    key-store: classpath:arbfintech_cert.jks
    key-store-password: Arb@8888
    keyAlias: arbfintech

spring:
  profiles: slave-54
  application:
    name: station-panda
  mvc:
    static-path-pattern: /**
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: -1
      max-request-size: -1
#  redis:
#    host: china-dev.vertical.arbcalls.com
#    port: 6379
#    password: arbfintech
#    timeout: 1000
#    pool:
#      max-active: -1
ribbon:
  read-timout: 60000
  connect-timeout: 60000
  eager-load:
    enabled: true
    clients: maintenance-restapi,microservice-business,oauth-server,cache-server,microservice-collect,microservice-lead,microservice-loan,microservice-payment
