#自定义配置
arb:
  service:
    name: microservice-loan
    port: 8201

server:
  max-http-header-size: 10240000
  port: 8201
eureka:
  instance:
    instance-id: 192.168.0.54:microservice-loan:8201
    hostname: 192.168.0.54
    ip-address: 192.168.0.54
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://192.168.0.54:8901/eureka/
feign:
  client:
    config:
      microservice-payment:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-transaction:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-timeline:
        connectTimeout: 600000
        readTimeout: 600000
      microservice-business:
        connectTimeout: 600000
        readTimeout: 600000
      cache-server:
        connectTimeout: 600000
        readTimeout: 600000
  httpclient:
    connection-timeout: 60000
ribbon:
  read-timout: 60000
  connect-timeout: 60000
  eager-load:
    enabled: true
    clients: microservice-business,cache-server
spring:
  application:
    name: microservice-loan
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
    test-on-borrow: true                      # 指明是否从池中取出连接前进行检验，如果检验失败，则从池中取出连接并尝试取出另一个
    test-while-idle: true                     # 指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
    time-between-eviction-runs-millis: 60000  # 在空闲连接回收器线程运行期间休眠的时间值，姨毫秒为单位。如果设置为非整数，则不运行空闲连接回收器线程
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 256Mb
      max-request-size: 256Mb
  jpa:
    database: mysql  #only worked for mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect #only worked for mysql
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect  #only worked for h2
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
