#自定义配置
arb:
  service:
    name: microservice-business
    port: 8802
    
eureka:
  instance:
    instance-id: ${arb.service.url}:${spring.application.name}:${server.port}
    hostname: ${arb.service.url}
    ip-address: ${arb.service.url}
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://${arb.eureka.url}:8901/eureka/

spring:
  application:
    name: ${arb.service.name}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${arb.database.url}/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: ${arb.database.username}
    password: ${arb.database.password}
    test-on-borrow: true                      # 指明是否从池中取出连接前进行检验，如果检验失败，则从池中取出连接并尝试取出另一个
    test-while-idle: true                     # 指明连接是否被空闲连接回收器（如果有）进行检验，如果检测失败，则连接将被从池中去除
    time-between-eviction-runs-millis: 60000  # 在空闲连接回收器线程运行期间休眠的时间值，姨毫秒为单位。如果设置为非整数，则不运行空闲连接回收器线程
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
    show-sql: false

feign:
  client:
    config:
      cache-server:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-maintenance:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-payment:
        connectTimeout: 60000
        readTimeout: 60000
      microservice-collect:
        connectTimeout: 60000
        readTimeout: 60000
  httpclient:
    connection-timeout: 60000

server:
  max-http-header-size: 10240000
  port: ${arb.service.port}
logging:
  config: classpath:log4j2.yml


arb:
  eureka:
    url: 192.168.0.54
  service:
    url: 192.168.0.54
  database:
    url: 192.168.0.100
    username: root
    password: Arbfintech@123
  rabbitmq:
    url: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
