eureka:
  instance:
    instance-id: 192.168.0.54:maintenance-restapi:8501
    hostname: 192.168.0.54
    ip-address: 192.168.0.54
    prefer-ip-address: true

  #    lease-renewal-interval-in-seconds: 10
  #    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://192.168.0.54:8901/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
    httpclient:
      connection-timeout: 60000
server:
  max-http-header-size: 10240000
  port: 8501
spring:
  application:
    name: maintenance-restapi
  cloud:
    inetutils:
      use-only-site-local-interfaces: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.100/panda?charset=utf8mb4&useSSL=false&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: Arbfintech@123
    filters: stat,wall,log4j
    initial-size: 5
    min-evictable-idle-time-millis: 300000
    min-idle: 5
    max-active: 20
    max-pool-prepared-statement-per-connection-size: 20
    max-wait: 60000
    pool-prepared-statements: true
    time-between-eviction-runs-millis: 60000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    validation-query: SELECT 1 FROM DUAL
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 256Mb
      max-request-size: 256Mb
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
encrypt:
  fail-on-error: false
ribbon:
  eager-load:
    enabled: true
    clients: cache-server
