server:
  max-http-header-size: 10240000
  port: 8905
eureka:
  instance:
    instance-id: 192.168.0.54:cache-server:8905
    hostname: 192.168.0.54
    ip-address: 192.168.0.54
    prefer-ip-address: true

#    lease-renewal-interval-in-seconds: 10
#    lease-expiration-duration-in-seconds: 30
  client:
    healthcheck: enabled
    service-url:
      defaultZone: http://192.168.0.54:8901/eureka/
spring:
  application:
    name: cache-server
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: Arbfintech
    password: Arbfintech
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    database: 10
    host: 192.168.0.100
    password: arbfintech
    port: 6379
